name: testCI workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  #  Run build unit tests to make sure everything is 👍
  build:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 'Check out repo'

      - name: User the latest stable Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          cache: 'npm'

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Run build'
        run: npm run build

      - name: 'Run unit tests'
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        name: ' check out repo'

      - name: 'install dependencies'
        run: npm ci

      - name: 'run lint'
        run: npm run lint
